config/routes.rb
Rails.application.routes.draw do
  #limit routes to only these 4
  resources :messages, :only => [:index, :new, :create, :show]

  root :to => 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_sms

private
  def send_sms
    begin
    response = RestClient::Request.new(
      :method => :post,
      :url => 'https://api.twilio.com/2010-04-01/Accounts/AC92343d189fc553f58a92f9895da8ced5/Messages.json',
      :user => ENV['Twilio_Acc_Sid'],
      :password => ENV['Twilio_Auth_Token'],
      :payload => { :Body => body,
                    :From => from,
                    :To => to}
    ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      throw(:abort) #helping it not crash if it fails to save
    end
  end
end

# This part is an exception finding an specificly the bad request error
# RestClient::BadRequest => error
#   message = JSON.parse(error.response)['message']
#   errors.add(:base, message)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def index
  @messages = Message.all
end

def new
  @message = Message.new
end

def create
  @message = Message.new(message_params)
  if @message.save
    flash[:notice] = "Sent!"
    redirect_to messages_path
  else
    render 'new'
  end
end

def show
  @message = Message.find(params[:id])
end

private

 def message_params
   params.require(:message).permit(:to, :from, :body)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwilioRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.body, message_path(message) %></li>
  <% end %>
</ul>
<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>Something wen wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end  %>